// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCookieExpiry(arg1) {
  return window['go']['main']['WailsApp']['CheckCookieExpiry'](arg1);
}

export function ClearLogFile() {
  return window['go']['main']['WailsApp']['ClearLogFile']();
}

export function FormatCookieForDisplay(arg1) {
  return window['go']['main']['WailsApp']['FormatCookieForDisplay'](arg1);
}

export function GetConfig() {
  return window['go']['main']['WailsApp']['GetConfig']();
}

export function GetCookieGuide() {
  return window['go']['main']['WailsApp']['GetCookieGuide']();
}

export function GetCookieScript() {
  return window['go']['main']['WailsApp']['GetCookieScript']();
}

export function GetLogFilePath() {
  return window['go']['main']['WailsApp']['GetLogFilePath']();
}

export function GetLogFileSize() {
  return window['go']['main']['WailsApp']['GetLogFileSize']();
}

export function GetQuota() {
  return window['go']['main']['WailsApp']['GetQuota']();
}

export function GetServiceStatus() {
  return window['go']['main']['WailsApp']['GetServiceStatus']();
}

export function OpenLogDirectory() {
  return window['go']['main']['WailsApp']['OpenLogDirectory']();
}

export function OpenMonicaLogin() {
  return window['go']['main']['WailsApp']['OpenMonicaLogin']();
}

export function StartService() {
  return window['go']['main']['WailsApp']['StartService']();
}

export function StopService() {
  return window['go']['main']['WailsApp']['StopService']();
}

export function TestConfig() {
  return window['go']['main']['WailsApp']['TestConfig']();
}

export function TestMonicaConnection() {
  return window['go']['main']['WailsApp']['TestMonicaConnection']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['WailsApp']['UpdateConfig'](arg1);
}

export function ValidateCookie(arg1) {
  return window['go']['main']['WailsApp']['ValidateCookie'](arg1);
}
