#!/bin/bash
echo "=== Monica 代理配置指南 ==="
echo ""
echo "我已经更新了 OpenClaw 配置，添加了 Monica 提供商。"
echo "现在需要你完成 Monica 代理的配置。"
echo ""

echo "步骤1: 确保 Monica GUI 已打开"
echo "如果还没有打开，请运行:"
echo "cd /Users/wlli/Documents/project/openclaw/monica2api"
echo "./build/bin/monica-proxy-wails.app/Contents/MacOS/monica-proxy-wails"
echo ""

echo "步骤2: 在 Monica GUI 中配置"
echo "1. 点击'获取助手'按钮获取 Cookie"
echo "2. 在 Bearer Token 输入框中输入:"
echo "   d1b9422d7b6f18b863dd212a5ea699fdf7cf9e2dcbcf5a8c4630565f176949c2"
echo "3. 点击'启动服务'按钮"
echo ""

echo "步骤3: 验证服务"
echo "打开新终端，运行测试命令:"
echo "curl -X POST 'http://localhost:8080/v1/chat/completions' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer d1b9422d7b6f18b863dd212a5ea699fdf7cf9e2dcbcf5a8c4630565f176949c2' \\"
echo "  -d '{\"model\":\"gpt-5.4\",\"messages\":[{\"role\":\"user\",\"content\":\"Hello\"}]}'"
echo ""

echo "步骤4: 测试 OpenClaw 集成"
echo "在飞书中发送消息:"
echo "@OpenClaw 使用 monica：你好，测试 gpt-5.4"
echo "或"
echo "@OpenClaw /model monica/gpt-5.4 你好，测试"
echo ""

echo "=== 配置信息总结 ==="
echo "提供商: monica"
echo "API地址: http://localhost:8080/v1"
echo "Bearer Token: d1b9422d7b6f18b863dd212a5ea699fdf7cf9e2dcbcf5a8c4630565f176949c2"
echo "默认模型: gpt-5.4"
echo "支持模型:"
echo "  - gpt-5.4 (别名: monica)"
echo "  - gpt-5.3"
echo "  - gpt-5.3-codex"
echo "  - claude-4.6-sonnet"
echo "  - claude-4.5-haiku"
echo "  - gemini-3-flash"
echo "  - gemini-3-pro"
echo "  - gemini-3.1-pro"
echo "  - grok-4"
echo "  - grok-code-fast-1"
echo ""

echo "=== 故障排除 ==="
echo "如果测试失败:"
echo "1. 检查 Monica GUI 是否显示'服务运行中'"
echo "2. 检查端口 8080 是否监听: lsof -i :8080"
echo "3. 重新启动 Monica 代理"
echo "4. 重新获取 Cookie"
echo ""

echo "配置完成后，在飞书中测试:"
echo "@OpenClaw 使用 monica 的 gpt-5.4：帮我写代码/分析问题"